### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by pratyush3124**
Ported to Python3 form Python2

### CODE REVIEW

**Comment by walterbender** [comment]
I see quite a few errors but not necessarily from Python3 conversion. Can you please check?

/simon-says-activity/
/home/walter/Activities/simon-says-activity/activity.py:4: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded

Attempting to add a widget with type GtkGrid to a activity+SimonSaysActivity, but as a GtkBin subclass a activity+SimonSaysActivity can only contain one widget at a time; it already contains a widget of type GtkVBox

**Comment by Hrishi1999** [comment]
Please add `import gi`,
`gi.require_version('Gtk', '3.0')` on top of all the imports.
Edit: Sorry, I meant in the main program :)

**Comment by quozl** [comment]
> Please add `import gi`,
> `gi.require_version('Gtk', '3.0')` on top of all the imports.

No, only one is needed, in the main program.

**Comment by quozl** [comment]
Thanks.  Reviewed.  There's a _Gtk.CssProvider_ used, but no changes to string constants, so it looks like you haven't read the Port to Python 3 guide or tested the activity.  Please test before commit.

**Comment by quozl** [comment]
Tested on Ubuntu 19.10.  It doesn't work.

```log
Traceback (most recent call last):
  File "/usr/share/sugar/activities/SimonSays.activity/activity.py", line 137, in start_game
    load_css(css)
  File "/usr/share/sugar/activities/SimonSays.activity/activity.py", line 45, in load_css
    style_provider.load_from_data(css)
TypeError: Item 0: Must be number, not str
```

However, @walterbender says it works on Fedora 30.

**Comment by pratyush3124** [comment]
Ya sorry sir. I will edit and test.

**Pull request closed without merging**
